name: 'Check ranking for all keywords'
on:
  schedule:
    - cron: '0 0 * * *'  # This schedule runs the job every day at midnight UTC

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl -X GET 'https://nishkun-rank-tracker.vercel.app/api/check-for-all-keywords'
